/*
 * Copyright (c) 2026. Bernard Bou
 */

apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

android {

    namespace "org.treebolic.wordnet.provider.kwi"

    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.fromTarget("17")
    }
}

dependencies {
    implementation project(':treebolicGlue')

    implementation "io.github.treebolic:treebolic-view:${treebolicVersion}"
    implementation "io.github.treebolic:treebolic-mutable:${treebolicVersion}"
    implementation "io.github.treebolic:treebolic-view:${treebolicVersion}"
    implementation "io.github.treebolic:treebolic-loadbalancer:${treebolicVersion}"
    implementation "io.github.treebolic:provider-wordnet-kwi:${treebolicVersion}"
    implementation 'io.github.oewntk:kwi:3.0.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.annotation:annotation:1.9.1'

    implementation 'androidx.core:core-ktx:1.15.0'
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:${desugaringVersion}"
}
